# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "zero-ui"
version = "0.1.3"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "zero-ui for use in zero projects"
homepage = "https://zero-company.pages.dev/"
repository = "https://github.com/zero-company/zero-ui"
readme = "./../../../README.md"
categories = ["zero", "gui"]
keywords = ["zero", "leptos", "components", "component-library"]

[dependencies]
leptos = { workspace = true }
leptos-use = { workspace = true }
anyhow = { version = "1.0.75" }
thiserror = { version = "1.0.50" }
tar = { version = "0.4.40" }
fs_extra = { version = "1.3.0" }
include_dir = { version = "0.7.3" }
leptos_icons = { version = "0.1.0" }
icondata_core = { version = "0.0.2" }

[features]
csr = ["leptos/csr"]
ssr = ["leptos/ssr", "leptos-use/ssr"]
hydrate = ["leptos/hydrate"]
