[package]
name = "zero-ui"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "zero-ui for use in zero projects"
homepage = "https://zero-company.pages.dev/"
repository = "https://github.com/zero-company/zero-ui"

readme = "./../../../README.md"

[dependencies]
