[package]
name = "zero-ui"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "zero-ui for use in zero projects"
homepage = "https://zero-company.pages.dev/"
repository = "https://github.com/zero-company/zero-ui"
readme = "./../../../README.md"
categories = ["zero", "gui"]
keywords = ["zero", "leptos", "components", "component-library"]

[dependencies]
leptos = { workspace = true }
leptos-use = { workspace = true }

[features]
csr = ["leptos/csr"]
ssr = ["leptos/ssr", "leptos-use/ssr"]
hydrate = ["leptos/hydrate"]
