# Docs: https://github.com/thedodd/trunk/blob/master/Trunk.toml
[build]
filehash = false
release = true

#[[hooks]]
#stage = "post_build"
#command = "cp"
#command_arguments = [
#  "dist/.stage/zero-ui-base.css",
#  "src/assets/css/zero-ui.css",
#]
