# Docs: https://github.com/sagiegurari/cargo-make#usage-workspace-support-skip-include-members
[config]
default_to_workspace = false
# cli: cargo make --no-workspace run

[tasks.build-zero-ui]
dependencies = ["build-zero-ui-css", "copy-zero-ui-css"]
# workspace = false

[tasks.build-zero-ui-css]
description = "Generate tailwind css for zero-ui"
install_crate = "trunk"
command = "trunk"
args = ["build"]
cwd = "packages/zero-ui"

[tasks.copy-zero-ui-css]
description = "Copy zero-ui css outside of gitignored dist"
command = "cp"
args = ["dist/zero-ui-base.css", "src/assets/css/zero-ui.css"]
cwd = "packages/zero-ui"

[tasks.build-zero-ui-leptos]
description = "Build zero-ui CSR docs"
install_crate = "trunk"
command = "trunk"
args = ["build"]
cwd = "packages/zero-ui-leptos"

[tasks.unpack-zero-ui-leptos]
description = "Unpack zero-ui assets in zero-ui-leptos"
command = "cargo"
args = [
  "run",
  "--bin unpack-zero-ui-assets",
  "--",
  "--workspace zero-ui-leptos",
]
